version: '3'

services:
  golang120:
    image: golang:1.20
    container_name: golang120
    restart: always
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - '/wwwroot:/var/www/wwwroot'
    network_mode: "bridge"