version: '3.1'

services:
  mysql8.0:
    image: mysql:8.0.26
    container_name: mysql8.0
    restart: always
    ports:
      - 3380:3306
    volumes:
      - ./conf:/etc/mysql
      - ./logs:/var/log/mysql
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    network_mode: "bridge"