version: '3.1'

services:

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 28117:27017
    volumes:
      - ./db:/data/db # 挂载数据目录
      - ./logs:/var/log/mongodb  # 挂载日志目录
      - ./config:/etc/mongo  # 挂载配置目录
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} # root账户
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} # root密码
    network_mode: "bridge"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 28081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      # ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    network_mode: "bridge"